mandrill_api_key: "api_key"
mandrill_username: "username"
sentry_dsn: "api_key"


S3_BUCKET_NAME: "bucket_name"
AWS_ACCESS_KEY_ID: "AJSDLKJASLKDJAUASD"
AWS_SECRET_ACCESS_KEY: "asjdllaDSADJLASJASDSALDJALSDJLlkasjdlksad123123123"
AWS_REGION: "eu-west-1"

development:
  STRIPE_SECRET_KEY: "asjdllaDSADJLASJ(ASDSALDJALSDJLlkasjdlksad123123123"
  STRIPE_PUBLISHABLE_KEY: "asjdllaDSADJLASJASDSALDJALSDJLlkasjdlksad123123123"

test:
  STRIPE_SECRET_KEY: "asjdllaDSADJLASJ(ASDSALDJALSDJLlkasjdlksad123123123"
  STRIPE_PUBLISHABLE_KEY: "asjdllaDSADJLASJASDSALDJALSDJLlkasjdlksad123123123"

production: 
  STRIPE_SECRET_KEY: "asjdllaDSADJLASJ(ASDSALDJALSDJLlkasjdlksad123123123"
  STRIPE_PUBLISHABLE_KEY: "asjdllaDSADJLASJASDSALDJALSDJLlkasjdlksad123123123"